language: python
python:
  - "3.7"

addons:
  ssh_known_hosts: jedcua.dev

install:
  - pip install -r requirements.txt

before_install:
  - openssl aes-256-cbc -K $encrypted_88b3811b7945_key -iv $encrypted_88b3811b7945_iv
    -in travis_rsa.enc -out travis_rsa -d
  - chmod 600 travis_rsa
  - mv travis_rsa ~/.ssh/id_rsa

script:
  - mkdocs build

after_success:
  - bash ./deploy.sh
