site_name: Jed Cua
site_url: 'https://jedcua.dev'

theme: 
  name: material
  favicon: 'jedcua_icon.svg'
  logo: 'img/jedcua_small.svg'
  feature:
    tabs: false
  palette:
    primary: 'teal'

extra:
  disqus: 'jedcua'

extra_css:
  - extra.css

nav:
  - Home: 'index.md'
  - Projects: 
    - 'RPi Stacker' : 'projects/rpi_stacker.md'
  - Articles:
    - 'VirtualEnv' : 'articles/virtualenv.md'

markdown_extensions:
  - codehilite:
      guess_lang: false
      use_pygments: True
      noclasses: True
      pygments_style: monokai
